# -*- coding: utf-8 -*-
"""pythonKaniyam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWWNIPDjW7ryARK8VjsaLbp3LMBebIHP
"""

# python grade for exams
# check two conditions
mark = int(input("Enter your mark: "))

if mark >=91 and mark <=100:
  print("Grade A")
elif mark >=81 and mark <=90:
  print("Grade B")
elif mark >= 71 and mark <=80:
  print("Grade C")
elif mark >= 61 and mark <=70:
  print("Grade D")
elif mark >= 46 and mark <= 60:
  print("Gdrade E")
elif mark < 46  :
  print("Fail")
else:
  print("The mark is not valid")

is_pass = int(input("You passed examination: "))

if is_pass:
  if int(input("Are you passed with distinction: ")):
    if int(input("are you in top 2 students:")):
      print("Gold medal with first class distinction")
    else:
      print("first class with distinction")
  else:
    print("Degree graduate")
else:
  print("soon to be gradute")

# and logical
# let's make biriyani

rice = True
spices = True

is_delicious = rice and spices
print("Is biriyani delicious: ",is_delicious)

